version: "1.0"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: lostinfo
        container_name: lostinfo-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - lostinfo
        ports:
            - "8000:8000"
    db:
        image: mysql:8.0
        container_name: lostinfo-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "3306:3306"
        networks:
            - lostinfo
networks:
    lostinfo:
        driver: bridge
