version: "1.0"
services:
    app:
        build:
            args:
                user: ian
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: lostinfo
        container_name: lostinfo-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - lostinfo
    db:
        image: mysql:8.0
        container_name: lostinfo-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - lostinfo
    nginx:
        image: nginx:1.17-alpine
        container_name: lostinfo-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - lostinfo
networks:
    lostinfo:
        driver: bridge
